# Usage examples

## Imports

In [2]:
import sympy as sp

### axisangle_rotation.py

In [18]:
from axisangle_rotation import *

# Unit vector
r = (np.sqrt(2)/2)*np.array([0, -1, 1])

# Rotation angle
theta = np.pi/6

# Rotation matrix
R = axisangle_rotation(r=r, theta=theta)
print(R)

[[ 0.8660254  -0.35355339  0.35355339]
 [ 0.35355339  0.9330127  -0.0669873 ]
 [ 0.35355339 -0.0669873   0.9330127 ]]


### compute_jacobian.py

Displays the Jacobian matrix. Example with the 2R planar robot arm:

In [16]:
from compute_jacobian import compute_jacobian

theta1, theta2, l1, l2 = sp.symbols('theta1 theta2 l1 l2')

# 2R Forward Kinematics
x = l1 * sp.cos(theta1) + l2 * sp.cos(theta1 + theta2)
y = l1 * sp.sin(theta1) + l2 * sp.sin(theta1 + theta2)

functions = [x, y]
variables = [theta1, theta2]

J = compute_jacobian(functions, variables)

sp.pprint(J)

⎡-l₁⋅sin(θ₁) - l₂⋅sin(θ₁ + θ₂)  -l₂⋅sin(θ₁ + θ₂)⎤
⎢                                               ⎥
⎣l₁⋅cos(θ₁) + l₂⋅cos(θ₁ + θ₂)   l₂⋅cos(θ₁ + θ₂) ⎦


### determinant.py

In [ ]:
from determinant import determinant

theta1, theta2, l1, l2 = sp.symbols('theta1 theta2 l1 l2')

M = sp.Matrix([[l1 * sp.cos(theta1) + l2 * sp.cos(theta1 + theta2)],
               [l1 * sp.sin(theta1) + l2 * sp.sin(theta1 + theta2)],
               ])

J = compute_jacobian(M, variables=[theta1, theta2])

det_J = determinant(J)

== Determinant of the matrix ==
l₁⋅l₂⋅sin(θ₂)


### DH_matrix.py

Displays the Denavit-Hartenberg transformation matrix

In [19]:
from DH_matrix import DH_matrix

DH_mat = DH_matrix()
sp.pprint(DH_mat)

⎡cos(θ)  -sin(θ)⋅cos(α)  -sin(α)⋅sin(θ)  a⋅cos(θ)⎤
⎢                                                ⎥
⎢sin(θ)  cos(α)⋅cos(θ)   -sin(α)⋅cos(θ)  a⋅sin(θ)⎥
⎢                                                ⎥
⎢  0         sin(α)          cos(α)         d    ⎥
⎢                                                ⎥
⎣  0           0               0            1    ⎦


### euler_rotation.py

In [22]:
from euler_rotation import euler_rotation


angles = [np.pi/2, np.pi/4, -np.pi/4]

R = euler_rotation(sequence='xyz', angles=angles)

print(R)

[[ 5.00000000e-01  5.00000000e-01  7.07106781e-01]
 [ 5.00000000e-01  5.00000000e-01 -7.07106781e-01]
 [-7.07106781e-01  7.07106781e-01  4.32978028e-17]]


### find_null.py

In [ ]:
from find_null import find_null

J = sp.Matrix([[-1, 0, 1],
               [0, 0, 0],
               ])

find_null(J)

Null space of the matrix:
Basis vector n°1:
⎡0⎤
⎢ ⎥
⎢1⎥
⎢ ⎥
⎣0⎦
Basis vector n°2:
⎡1⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣1⎦


### find_range.py

In [ ]:
from find_range import find_range

J = sp.Matrix([[-1, 0, 1],
               [0, 0, 0],
               ])

find_range(J)

Range of the Jacobian:
Basis vector n°1:
⎡-1⎤
⎢  ⎥
⎣0 ⎦


### transform_matrix.py

In [20]:
from transform_matrix import transform_matrix

DH_table = [[0, 0.5, 1, sp.pi/4],
            [-sp.pi/2, 0.3, 0.2, sp.pi/6],
            [0, 0.2, 0.4, sp.pi/3],]

T = transform_matrix(DH_table=DH_table, x=0, y=2)
sp.pprint(T)

⎡     -√3            ⎤
⎢1/2  ────  0   0.1  ⎥
⎢      2             ⎥
⎢                    ⎥
⎢√3                  ⎥
⎢──   1/2   0  0.1⋅√3⎥
⎢2                   ⎥
⎢                    ⎥
⎢ 0    0    1   0.4  ⎥
⎢                    ⎥
⎣ 0    0    0    1   ⎦


The numerical result can be obtained with evalf()

In [ ]:
T_numerical = T.evalf()
sp.pprint(T_numerical)

⎡       0.5         -0.866025403784439   0          0.1       ⎤
⎢                                                             ⎥
⎢0.866025403784439         0.5           0   0.173205080756888⎥
⎢                                                             ⎥
⎢        0                  0           1.0         0.4       ⎥
⎢                                                             ⎥
⎣        0                  0            0          1.0       ⎦
